name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Install WASIX toolchain
        run: |
          bash lib/setup-wasix.sh
      - name: Run tests
        run: |
          export WASIX_SYSROOT=/wasix-sysroot
          export WASMER=/usr/bin/wasmer
          export TERM=xterm-256color
          bash test.sh | tee test.log
      - name: Summarize test results
        run: |
          bash lib/summarize-test-results-for-ci.sh
      - name: Post test results to PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = './pr_comment.txt';
            if (!fs.existsSync(path)) {
              core.setFailed('Comment file not found');
              return;
            }
            const content = fs.readFileSync(path, 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            });
