name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Install WASIX toolchain
        run: |
          sudo apt update > /dev/null
          sudo apt install -y clang llvm git git-lfs build-essential make cmake libtool pkg-config yq expect > /dev/null

          curl -sSf https://raw.githubusercontent.com/wasix-org/wasix-clang/refs/heads/main/setup.sh | bash
      - name: Run tests
        run: |
          source ~/.wasix-clang/activate
          bash test.sh exit-* | tee test.log
      - name: Summarize test results
        run: |
          bash -x lib/summarize-test-results-for-ci.sh
      - name: Post test results to PR
        uses: actions/github-script@v7
        if: github.event.pull_request.base.ref == 'master'
        with:
          script: |
            const fs = require('fs');
            const path = './pr_comment.txt';
            if (!fs.existsSync(path)) {
              core.setFailed('Comment file not found');
              return;
            }
            const content = fs.readFileSync(path, 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            });
