name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Install WASIX toolchain
        run: |
          bash lib/setup-wasix.sh
      - name: Run tests
        run: |
          export WASIX_SYSROOT=/wasix-sysroot
          export TERM=xterm-256color
          bash test.sh | tee test.log
      - name: Summarize test results
        run: |
          bash lib/summarize-test-results-for-ci.sh
      - name: Post results to PR
        uses: EliLillyCo/github-actions-post-to-pr@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          post_to_pr_definition: |
            [
              {
                "message_file": "./pr_comment.txt",
                "title": "Test Results",
                "collapsible": true
              }
            ]
